start-at-login = true
automatically-unhide-macos-hidden-apps = true
accordion-padding = 5

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# Anything that has LB-SCRATCH in the window title goes to scratchpad mode (floating)
[[on-window-detected]]
if.window-title-regex-substring = 'LB-SCRATCH'
check-further-callbacks = true
run = ['layout floating']

[mode.main.binding]

ctrl-enter = 'exec-and-forget open -na /Applications/kitty.app --args -1'
# Clashes with jupyter execute-and-remain-on cell
# cmd-enter = 'exec-and-forget open -na /Applications/kitty.app --args -1'

cmd-f1 = 'exec-and-forget /usr/bin/python3 ~/.local/bin/aerospace_scratch LB-SCRATCH-JUPYTER RECENTER /Applications/kitty.app --args -T LB-SCRATCH-JUPYTER --instance-group scratch -o hide_window_decorations=titlebar-only ~/sci-env/bin/jupyter console --ZMQTerminalInteractiveShell.banner='
cmd-f2 = 'exec-and-forget /usr/bin/python3 ~/.local/bin/aerospace_scratch LB-SCRATCH-LBQQ NOCENTER /Users/lb/sci-env/bin/lbqq --id LB-SCRATCH-LBQQ --title LB-SCRATCH-LBQQ --url https://chatgpt.com/g/g-p-68eb6162e0448191b758e04935fbf660-qqs/project'

cmd-1 = 'summon-workspace 1'
cmd-2 = 'summon-workspace 2'
cmd-3 = 'summon-workspace 3'
cmd-4 = 'summon-workspace 4'
cmd-5 = 'summon-workspace 5'
cmd-6 = 'summon-workspace 6'
cmd-7 = 'summon-workspace 7'
cmd-8 = 'summon-workspace 8'
cmd-9 = 'summon-workspace 9'
cmd-0 = 'summon-workspace 0'

cmd-shift-1 = ['move-node-to-workspace 1', 'summon-workspace 1']
cmd-shift-2 = ['move-node-to-workspace 2', 'summon-workspace 2']
cmd-shift-3 = ['move-node-to-workspace 3', 'summon-workspace 3']
cmd-shift-4 = ['move-node-to-workspace 4', 'summon-workspace 4']
cmd-shift-5 = ['move-node-to-workspace 5', 'summon-workspace 5']
cmd-shift-6 = ['move-node-to-workspace 6', 'summon-workspace 6']
cmd-shift-7 = ['move-node-to-workspace 7', 'summon-workspace 7']
cmd-shift-8 = ['move-node-to-workspace 8', 'summon-workspace 8']
cmd-shift-9 = ['move-node-to-workspace 9', 'summon-workspace 9']
cmd-shift-0 = ['move-node-to-workspace 0', 'summon-workspace 0']

ctrl-slash = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

ctrl-backtick = 'focus-back-and-forth'
ctrl-h = 'focus left --boundaries-action wrap-around-the-workspace'
ctrl-j = 'focus down --boundaries-action wrap-around-the-workspace'
ctrl-k = 'focus up --boundaries-action wrap-around-the-workspace'
ctrl-l = 'focus right --boundaries-action wrap-around-the-workspace'
ctrl-left = 'focus left --boundaries-action wrap-around-the-workspace'
ctrl-down = 'focus down --boundaries-action wrap-around-the-workspace'
ctrl-up = 'focus up --boundaries-action wrap-around-the-workspace'
ctrl-right = 'focus right --boundaries-action wrap-around-the-workspace'

ctrl-shift-h = 'join-with left'
ctrl-shift-j = 'join-with down'
ctrl-shift-k = 'join-with up'
ctrl-shift-l = 'join-with right'
ctrl-shift-left = 'join-with left'
ctrl-shift-down = 'join-with down'
ctrl-shift-up = 'join-with up'
ctrl-shift-right = 'join-with right'

ctrl-shift-m = 'fullscreen --no-outer-gaps'
ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

ctrl-shift-r = 'reload-config'

ctrl-esc = 'mode service'
ctrl-m = 'mode move'

[mode.move.binding]

h = ['move left', 'mode main']
j = ['move down', 'mode main']
k = ['move up', 'mode main']
l = ['move right', 'mode main']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
l = ['exec-and-forget pmset displaysleepnow', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']
